name: flutter_app_search
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx:
  barcode_scan: ^1.0.0
  flutter_mobx:
  provider:
  http: ^0.12.0+2
  material_design_icons_flutter: ^3.4.4795

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
