name: flutter_app_search
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx: ^1.0.2
  barcode_scan: ^1.0.0
  flutter_mobx: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  mobx_codegen: ^1.0.2

flutter:
  uses-material-design: true
